///
/// @file hV_Serial_System.h
/// @brief Save screen content to BMP and header files on SD card
///
/// @details Project Pervasive Displays Library Suite
/// @n Based on highView technology
///
/// @author Rei Vilo
/// @date 21 Jul 2023
/// @version 612
///
/// @copyright (c) Rei Vilo, 2010-2023
/// @copyright All rights reserved
///
/// * Evaluation edition: for professionals or organisations, no commercial usage
/// * Commercial edition: for professionals or organisations, for commercial usage
///

// SDK
#include "hV_HAL_Peripherals.h"

// Configuration
#include "hV_Configuration.h"

#ifndef hV_SERIAL_SYSTEM_RELEASE
///
/// @brief Release
///
#define hV_SERIAL_SYSTEM_RELEASE 612

#if (hV_HAL_PERIPHERALS_RELEASE < 607)
#error Required hV_HAL_PERIPHERALS_RELEASE 609
#endif // hV_HAL_PERIPHERALS_RELEASE

#if (STORAGE_MODE & USE_SERIAL_CONSOLE)
#warning STORAGE_MODE with USE_SERIAL_CONSOLE
#else
#error Required STORAGE_MODE with USE_SERIAL_CONSOLE
#endif // STORAGE_MODE

// Other libraries

///
/// @brief Screen printed to serial console
/// @warning Requires an SD-card library
///
class Serial_System
{
  public:
    ///
    /// @brief Constructor object
    /// @param screen &screen to link Serial_System to
    ///
    Serial_System();

    ///
    /// @brief File system and SD-card initialisation
    /// @param pinCS SD selection
    /// @param port SPI port, default = 0,
    /// @param pinDetect SD detection, default = -1 = none
    /// @param level expected level when SD-card available, default = LOW
    /// @return true if SD card available
    /// @warning FAT16 only SD-card
    /// @note Generally,
    /// @code {.cpp}
    /// myFileBMP.beginFileSystem(myBoard.cardCS);
    /// @endcode
    ///
    bool beginFileSystem(uint8_t pinCS = NOT_CONNECTED, uint8_t port = 0, int8_t pinDetect = -1, int level = LOW);

    ///
    /// @brief Close file system
    /// @return true is successful
    ///
    bool endFileSystem();

    ///
    /// @brief Set the folder for files
    /// @details The folder is created if it does not exist
    /// @param name folder name, ony letters and numbers
    /// @return RESULT_SUCCESS is successful, RESULT_ERRO otherwise
    /// @note Only for compatibility with Files, not implemented for Serial
    ///
#if (STRING_MODE == USE_STRING_OBJECT)

    bool setFolder(String name);

#elif (STRING_MODE == USE_CHAR_ARRAY)

    bool setFolder(const char * name);

#endif // STRING_MODE

    ///
    /// @brief Suspend file system
    /// @details Switch to main SPI and ensure SD-card /CS HIGH
    ///
    /// @return true is successful
    ///
    bool suspendFileSystem();

    ///
    /// @brief Resume file system after suspend
    /// @details Switch to SD-card SPI bus, if any
    ///
    /// @return true is successful
    ///
    bool resumeFileSystem();

    ///
    /// @brief Screen printed to serial console
    /// @param name file name, only letters and numbers
    /// @param multiplier size of each dot, default = 1
    /// * Recommended 2 for small screens
    /// * Otherwise 1 for medium and large screens
    /// @note The resulting BMP file is 5-5-5 coded.
    ///
#if (STRING_MODE == USE_STRING_OBJECT)

    void saveScreen(String name, uint8_t multiplier = 1);

#elif (STRING_MODE == USE_CHAR_ARRAY)

    void saveScreen(const char * name, uint8_t multiplier = 1);

#endif // STRING_MODE

    ///
    /// @brief Partial window printed to serial console
    /// @param name file name, only letters and numbers
    /// @param x0 top left coordinate, x-axis
    /// @param y0 top left coordinate, y-axis
    /// @param dx width to be copied, x-axis
    /// @param dy height to be copied, y-axis
    /// @param multiplier size of each dot, default = 1
    /// * Recommended 2 for small screens
    /// * Otherwise 1 for medium and large screens
    /// @note The resulting BMP file is 5-5-5 coded.
    ///
#if (STRING_MODE == USE_STRING_OBJECT)

    void saveWindow(String name, uint16_t x0, uint16_t y0, uint16_t dx, uint16_t dy, uint8_t multiplier = 1);

#elif (STRING_MODE == USE_CHAR_ARRAY)

    void saveWindow(const char * name, uint16_t x0, uint16_t y0, uint16_t dx, uint16_t dy, uint8_t multiplier = 1);

#endif // STRING_MODE

    ///
    /// @brief Load and display header file
    /// @param name file name
    /// @note The BMP file should be 5-5-5 coded.
    /// @param multiplier size of each dot, default = 1
    /// * Recommended 2 for small screens
    /// * Otherwise 1 for medium and large screens
    /// @warning Prefer BMP file generated by saveScreen()
    ///
#if (STRING_MODE == USE_STRING_OBJECT)

    void readScreen(String name, uint8_t multiplier = 1);

#elif (STRING_MODE == USE_CHAR_ARRAY)

    void readScreen(const char * name, uint8_t multiplier = 1);

#endif // STRING_MODE

    /// @cond
  protected:
    char _folderName[64] = {0};
    /// @endcond
};

#endif // hV_SERIAL_SYSTEM_RELEASE
